=== Izan701/LEMIProject/dtd/gamePass.dtd
<!ELEMENT gamePass (discount, vat, services, games)>
<!ELEMENT discount (#PCDATA)>
<!ELEMENT vat (#PCDATA)>
<!ELEMENT services (service+)>
<!ELEMENT service (name, price, includes, image)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ATTLIST price
          currency CDATA (€|$|£) "€">
<!ELEMENT includes (include+)>
<!ELEMENT include (#PCDATA)> 
<!ELEMENT image (#PCDATA)>
<!ELEMENT games (game+)>
<!ELEMENT game (name, image, platforms, price, release, dev, publisher, review)>
<!ATTLIST game
          id CDATA #REQUIRED>
<!ELEMENT platforms (platform+)>
<!ELEMENT platform (#PCDATA)>
<!ELEMENT release (#PCDATA)>
<!ELEMENT dev (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT review (#PCDATA)>

=== Izan701/LEMIProject/xml/gamePass.xml
<?xml version="1.0" encoding="UTF-8"?>
<gamePass xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../xsd/GamePass_schema.xsd">
<!-- <!DOCTYPE gamePass SYSTEM "../dtd/gamePass.dtd"> -->
    <discount>0.8</discount>
    <vat>21</vat>
    <services>
        <service>
            <name>Ultimate</name>
            <price currency="€">12.99</price>
            <includes>EA Play, Gold, XBOX Cloud Gaming, Games</includes>
            <image>images/gamePassUltimate.jpg</image>
        </service>

        <service>
            <name>PC</name>
            <price currency="€">9.99</price>
            <includes>EA play, Games</includes>
            <image>images/gamePass.png</image>
        </service>

        <service>
            <name>Console</name>
            <price currency="€">9.99</price>
            <includes>Games</includes>
            <image>images/gamePassConsole.jpg</image>
        </service>
    </services>
    <games>

        <game id="g001">
            <name>Forza Horizon 4 Standard Edition</name>
            <image>https://store-images.s-microsoft.com/image/apps.36093.14343301090572358.2000000000007864116.1feb0fed-abe9-4849-b638-8d7eca69cff4?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
                <platform>Mobile</platform>
            </platforms>
            <price currency="€">39.99</price>
	        <release>2018-09-28</release>
            <dev>Turn 10 Studios, Playground Games</dev>
            <publisher>Microsoft</publisher>
            <review>https://www.metacritic.com/game/xbox-one/forza-horizon-4</review>
        </game>
        <game id="g002">
            <name>Gang Beasts</name>
            <image>https://store-images.s-microsoft.com/image/apps.35593.68150164172276526.ddc374d7-ef5e-43b9-940a-bbc04440bb33.e0c05607-881c-449f-826b-fec43403598c?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
                <platform>Mobile</platform>
            </platforms>
            <price currency="€">19.99</price>
            <release>2014-08-29</release>
            <dev>Boneloaf, Coatsink</dev>
            <publisher>Double Fine, Skybound Games, Boneloaf</publisher>
            <review>https://www.metacritic.com/game/playstation-4/gang-beasts</review>
        </game>
        <game id="g003">
            <name>Halo Infinite</name>
            <image>https://store-images.s-microsoft.com/image/apps.13795.14330850369313893.ca028cc6-0250-4527-9563-95c2d95d43f8.f3983463-cc8b-453d-ade7-1530a454085f?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
            </platforms>
            <price currency="€">69.99</price>
	        <release>2021-12-08</release>
            <dev>343 Industries</dev>
            <publisher>Microsoft</publisher>
            <review>https://www.metacritic.com/game/xbox-series-x/halo-infinite</review>
        </game>
        <game id="g004">
            <name>HITMAN Trilogy</name>
            <image>https://store-images.s-microsoft.com/image/apps.43099.14144194933273826.3ced5741-3e78-4437-9d89-92e9ac9b74fc.5d72efb4-9b30-4b1a-8e97-adda6b1be68d?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
            </platforms>
            <price currency="€">59.99</price>
	        <release>2022-01-20</release>
            <dev>IO Interactive</dev>
            <publisher>IO Interactive</publisher>
            <review>https://www.metacritic.com/game/playstation-3/hitman-hd-trilogy</review>
        </game>
        <game id="g005">
            <name>Minecraft</name>
            <image>https://store-images.s-microsoft.com/image/apps.17382.13510798885735219.9735d495-578c-4a4c-b892-3eb3a780b3a0.d3792486-cf98-40c0-a2c1-d6443f0e2b70?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
                <platform>Mobile</platform>
            </platforms>
            <price currency="€">23.95</price>
	        <release>2011-11-18</release>
            <dev>Mojang, Microsoft</dev>
            <publisher>Microsoft</publisher>
            <review>https://www.metacritic.com/game/pc/minecraft</review>
        </game>
        <game id="g006">
            <name>Mortal Kombat 11</name>
            <image>https://store-images.s-microsoft.com/image/apps.9688.70804610839547354.8da93c46-fd13-4b16-8ebe-e8e02c53d93e.09c2e91e-28bd-4f6f-bfd6-79d6b241667a?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
                <platform>Mobile</platform>
            </platforms>
            <price currency="€">49.99</price>
	        <release>2019-04-22</release>
            <dev>NetherRealm Studios, QLOC, Shiver Entertainment</dev>
            <publisher>Warner Bros Interactive entertainment</publisher>
            <review>https://www.metacritic.com/game/playstation-4/mortal-kombat-11</review>
        </game>
        <game id="g007">
            <name>Sea of Thieves</name>
            <image>https://store-images.s-microsoft.com/image/apps.16347.14554784103656548.6c0bfca6-ceff-4368-9bde-2fe50f344136.007dce43-6492-46f2-bb2b-2b28df98fc3c?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
                <platform>Mobile</platform>
            </platforms>
	        <price currency="€">39.99</price>
	        <release>2018-03-20</release>
            <dev>Rare</dev>
            <publisher>Xbox Game Studios</publisher>
            <review>https://www.metacritic.com/game/xbox-one/sea-of-thieves</review>
        </game>
        <game id="g008">
            <name>Octopath Traveller</name>
            <image>https://store-images.s-microsoft.com/image/apps.35609.13539010844025035.cd25451c-c47c-45c8-b378-724488a9e769.f5b7bd24-0155-4432-a51f-ddf22fc1bbd7?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>PC</platform>
            </platforms>
            <price currency="€">44.99</price>
	        <release>2018-07-13</release>
            <dev>Square Enix, ACQUIRE Corp</dev>
            <publisher>Square Enix</publisher>
            <review>https://www.metacritic.com/game/pc/octopath-traveler</review>
        </game>
        <game id="g009">
            <name>Destiny 2</name>
            <image>https://store-images.s-microsoft.com/image/apps.15749.14134992626562533.45eb17c9-271a-401c-b19e-b47df75b7600.f4dee6b7-ed92-4bdb-8c66-a45238b9e9a1?q=90</image>
            <platforms>
                <platform>PC</platform>
            </platforms>
            <price currency="€">Free</price>
	        <release>2017-08-28</release>
            <dev>Bungie Studios</dev>
            <publisher>Bungie Studios, Activision</publisher>
            <review>https://www.metacritic.com/game/pc/destiny-2</review>
        </game>
        <game id="g010">
            <name>The Elder Scrolls V: Skyrim Special Edition</name>
            <image>https://store-images.s-microsoft.com/image/apps.64810.68326442227858632.03782b23-7f26-4a8e-ba87-177bdf2c3c90.fdefe49f-270c-44e5-b660-6d7764b37f0f?q=90</image>
            <platforms>
                <platform>Console</platform>
                <platform>Mobile</platform>
            </platforms>
            <price currency="€">39.99</price>
	        <release>2016-10-28</release>
            <dev>Bethesda Game Studios</dev>
            <publisher>Bethesda Softworks</publisher>
            <review>https://www.metacritic.com/game/pc/the-elder-scrolls-v-skyrim</review>
        </game>
        <game id="g011">
            <name>A Plague Tale: Innocence</name>
            <image>https://store-images.s-microsoft.com/image/apps.14356.68306748966338141.e6f96fac-aa67-4f59-9043-10654607aa79.aa73acc4-f944-4ab1-83c3-265506b1529d?q=90</image>
            <platforms>
                <platform>PC</platform>
            </platforms>
            <price currency="€">44.99</price>
	        <release>2020-01-23</release>
            <dev>Asobo Studio</dev>
            <publisher>Focus Home Interactive</publisher>
            <review>https://www.metacritic.com/game/pc/a-plague-tale-innocence</review>
        </game>
        <game id="g012">
            <name>Age of Empires Definitive Edition</name>
            <image>https://store-images.s-microsoft.com/image/apps.2072.13672427983916579.274b1ffd-9cde-4bef-9a3e-6f37073d5ed0.b81c0b81-e80e-4500-bdc7-0939f60b77bc?q=90</image>
            <platforms>
                <platform>PC</platform>
            </platforms>
            <price currency="€">19.99</price>
	        <release>2019-08-19</release>
            <dev>Forgotten Empires</dev>
            <publisher>Xbox Game Studios</publisher>
            <review>https://www.metacritic.com/game/pc/age-of-empires-definitive-edition</review>
        </game>
        <game id="g013">
            <name>My Friend Pedro</name>
            <image>https://store-images.s-microsoft.com/image/apps.40255.13688074046071077.6938c4a2-fd96-488f-af50-150fa03c98ef.4679ed83-05e2-4466-8fb3-6a72f2272cd8?q=90</image>
            <platforms>
                <platform>PC</platform>
            </platforms>
            <price currency="€">15.99</price>
	        <release>2019-12-05</release>
            <dev>Deadtoast</dev>
            <publisher>Devolver Digital</publisher>
            <review>https://www.metacritic.com/game/pc/my-friend-pedro</review>
        </game>
        
        <game id="g014">
            <name>Outer Wilds</name>
            <image>https://store-images.s-microsoft.com/image/apps.7475.67120997535715720.38c3e502-0019-4560-826e-634bbaf5cb4b.49bae061-49f7-4594-b2e4-17e7e25756ab?q=90</image>
            <platforms>
                <platform>Console</platform>
